// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112133315_updated")]
    partial class updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Models.MASTER.BRCH", b =>
                {
                    b.Property<string>("FranCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FRAN");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BRCH");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CREATEBY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CREATEREMARKS");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATETM");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NAMEAR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UPDATEBY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATEDT");

                    b.Property<string>("UpdateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UPDATEMARKS");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATETM");

                    b.HasKey("FranCode", "BranchCode");

                    b.ToTable("BRCH");
                });

            modelBuilder.Entity("ERP.Models.MASTER.FRAN", b =>
                {
                    b.Property<string>("FranCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FRAN");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CREATEBY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATEDT");

                    b.Property<string>("CreateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CREATEREMARKS");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATETM");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAMEAR");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UPDATEBY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATEDT");

                    b.Property<string>("UpdateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UPDATEMARKS");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATETM");

                    b.HasKey("FranCode");

                    b.ToTable("FRAN");
                });

            modelBuilder.Entity("ERP.Models.MASTER.PODET", b =>
                {
                    b.Property<string>("FranCode")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FRAN");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BRCH");

                    b.Property<string>("WhCode")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("WHSE");

                    b.Property<string>("VENDOR")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("VENDOR");

                    b.Property<string>("DOCTYPE")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DOCTYPE");

                    b.Property<string>("DOCNO")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DOCNO");

                    b.Property<string>("DOCSRL")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DOCSRL");

                    b.Property<decimal>("DISCOUNT")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("DISCOUNTVALUE")
                        .HasColumnType("numeric(22,0)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MAKE")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("PART")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("PRICE")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("QTY")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("REFNO")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("REFSRL")
                        .HasColumnType("numeric(22,0)");

                    b.Property<string>("REFTYPE")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("TOTALVALUE")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("VATPERCENTAGE")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("VATVALUE")
                        .HasColumnType("numeric(22,0)");

                    b.HasKey("FranCode", "BranchCode", "WhCode", "VENDOR", "DOCTYPE", "DOCNO", "DOCSRL");

                    b.HasIndex("VENDOR");

                    b.ToTable("PODET");
                });

            modelBuilder.Entity("ERP.Models.MASTER.POHDR", b =>
                {
                    b.Property<string>("FranCode")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FRAN");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BRCH");

                    b.Property<string>("WhCode")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("WHSE");

                    b.Property<string>("VENDOR")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("VENDOR");

                    b.Property<string>("DOCTYPE")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DOCTYPE");

                    b.Property<string>("DOCNO")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DOCNO");

                    b.Property<string>("CREATEBY")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("CREATEDT")
                        .HasColumnType("date");

                    b.Property<string>("CREATEREMARKS")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CREATETM")
                        .HasColumnType("datetime");

                    b.Property<string>("CURRENCY")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("DISCOUNT")
                        .HasColumnType("numeric(22,0)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("NOOFITEMS")
                        .HasColumnType("numeric(22,0)");

                    b.Property<decimal>("TOTALVALUE")
                        .HasColumnType("numeric(22,0)");

                    b.Property<string>("UPDATEBY")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("UPDATEDT")
                        .HasColumnType("date");

                    b.Property<string>("UPDATEMARKS")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UPDATETM")
                        .HasColumnType("datetime");

                    b.Property<string>("VENDORREFNO")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("VENDORREFTYPE")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("FranCode", "BranchCode", "WhCode", "VENDOR", "DOCTYPE", "DOCNO");

                    b.HasIndex("VENDOR");

                    b.ToTable("POHDR");
                });

            modelBuilder.Entity("ERP.Models.MASTER.Vendor", b =>
                {
                    b.Property<string>("VENDOR")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CREATEBY")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("CREATEDT")
                        .HasColumnType("date");

                    b.Property<string>("CREATEREMARKS")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CREATETM")
                        .HasColumnType("datetime");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NAMEAR")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UPDATEBY")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("UPDATEDT")
                        .HasColumnType("date");

                    b.Property<string>("UPDATEMARKS")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UPDATETM")
                        .HasColumnType("datetime");

                    b.Property<string>("VATNO")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("VENDOR");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("ERP.Models.MASTER.WHSE", b =>
                {
                    b.Property<string>("FranCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FRAN");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BRCH");

                    b.Property<string>("WhCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("WHSE");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CREATEBY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("CreateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CREATEREMARKS");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATETM");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NAMEAR")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UPDATEBY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATEDT");

                    b.Property<string>("UpdateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UPDATEMARKS");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATETM");

                    b.HasKey("FranCode", "BranchCode", "WhCode");

                    b.ToTable("WHSE");
                });

            modelBuilder.Entity("ERP.Models.MASTER.BRCH", b =>
                {
                    b.HasOne("ERP.Models.MASTER.FRAN", "FRAN")
                        .WithMany()
                        .HasForeignKey("FranCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FRAN");
                });

            modelBuilder.Entity("ERP.Models.MASTER.PODET", b =>
                {
                    b.HasOne("ERP.Models.MASTER.FRAN", "FRAN")
                        .WithMany()
                        .HasForeignKey("FranCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VENDOR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.BRCH", "BRCH")
                        .WithMany()
                        .HasForeignKey("FranCode", "BranchCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.WHSE", "WHSE")
                        .WithMany()
                        .HasForeignKey("FranCode", "BranchCode", "WhCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.POHDR", null)
                        .WithMany()
                        .HasForeignKey("FranCode", "BranchCode", "WhCode", "VENDOR", "DOCTYPE", "DOCNO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BRCH");

                    b.Navigation("FRAN");

                    b.Navigation("Vendor");

                    b.Navigation("WHSE");
                });

            modelBuilder.Entity("ERP.Models.MASTER.POHDR", b =>
                {
                    b.HasOne("ERP.Models.MASTER.FRAN", "FRAN")
                        .WithMany()
                        .HasForeignKey("FranCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VENDOR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.BRCH", "BRCH")
                        .WithMany()
                        .HasForeignKey("FranCode", "BranchCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.WHSE", "WHSE")
                        .WithMany()
                        .HasForeignKey("FranCode", "BranchCode", "WhCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BRCH");

                    b.Navigation("FRAN");

                    b.Navigation("Vendor");

                    b.Navigation("WHSE");
                });

            modelBuilder.Entity("ERP.Models.MASTER.WHSE", b =>
                {
                    b.HasOne("ERP.Models.MASTER.FRAN", "FRAN")
                        .WithMany()
                        .HasForeignKey("FranCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.MASTER.BRCH", "BRCH")
                        .WithMany()
                        .HasForeignKey("FranCode", "BranchCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BRCH");

                    b.Navigation("FRAN");
                });
#pragma warning restore 612, 618
        }
    }
}
