// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Models.MASTER.FRAN", b =>
                {
                    b.Property<string>("FranCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FRAN");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CREATEBY");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("CREATEDT");

                    b.Property<string>("CreateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CREATEREMARKS");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATETM");

                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(22, 0)")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NAMEAR");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UPDATEBY");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("UPDATEDT");

                    b.Property<string>("UpdateRemarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UPDATEMARKS");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATETM");

                    b.HasKey("FranCode");

                    b.ToTable("FRAN");
                });

            modelBuilder.Entity("ERP.Models.MASTER.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CREATEBY")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("CREATEDT")
                        .HasColumnType("date");

                    b.Property<string>("CREATEREMARKS")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CREATETM")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NAMEAR")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UPDATEBY")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("UPDATEDT")
                        .HasColumnType("date");

                    b.Property<string>("UPDATEMARKS")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UPDATETM")
                        .HasColumnType("datetime2");

                    b.Property<string>("VATNO")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VENDOR")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Vendor");
                });
#pragma warning restore 612, 618
        }
    }
}
